<div id="loading" class="loadingio-spinner-bars-6euccbu9ak2">
    <div class="ldio-erf14h1phsq">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
    </div>
</div>
<style type="text/css">
    @keyframes ldio-erf14h1phsq {
        0% {
            opacity: 1
        }

        50% {
            opacity: .5
        }

        100% {
            opacity: 1
        }
    }

    .ldio-erf14h1phsq div {
        position: absolute;
        width: 20px;
        height: 80px;
        top: 60px;
        animation: ldio-erf14h1phsq 1s cubic-bezier(0.5, 0, 0.5, 1) infinite;
    }

    .ldio-erf14h1phsq div:nth-child(1) {
        transform: translate(30px, 0);
        background: #ff5757;
        animation-delay: -0.6s;
    }

    .ldio-erf14h1phsq div:nth-child(2) {
        transform: translate(70px, 0);
        background: #ff4343;
        animation-delay: -0.4s;
    }

    .ldio-erf14h1phsq div:nth-child(3) {
        transform: translate(110px, 0);
        background: #ff5757;
        animation-delay: -0.2s;
    }

    .ldio-erf14h1phsq div:nth-child(4) {
        transform: translate(150px, 0);
        background: #ff4343;
        animation-delay: -1s;
    }

    .loadingio-spinner-bars-6euccbu9ak2 {
        width: 200px;
        height: 200px;
        display: inline-block;
        overflow: hidden;
        background: none;
    }

    .ldio-erf14h1phsq {
        width: 100%;
        height: 100%;
        position: relative;
        transform: translateZ(0) scale(1);
        backface-visibility: hidden;
        transform-origin: 0 0;
        /* see note above */
    }

    .ldio-erf14h1phsq div {
        box-sizing: content-box;
    }

    /* generated by https://loading.io/ */
</style>